### ISSUE TITLE
Simplify GUI for final steps

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/course-activity-planner#23]
Currently there are three buttons for saving at the end:

![image](https://cloud.githubusercontent.com/assets/7606540/14723774/bde90542-07e0-11e6-9a43-147efd5c5064.png)

My suggestion is to simplify this into two buttons:

PREVIEW (which implies a save, shows the PlanETS and regular previews) and DOWNLOAD MBZ (which implies a save).

**Comment by jdupl** [comment]
closed by 97677f4db10dad9163fa5e3f0d09ebe8dbd46fd0
