### ISSUE TITLE
Délivrer un programme permettant de parser un document XML provenant de Moodle.

### ISSUE THREAD

**Issue by denisbressand** [fuhrmanator/course-activity-planner#3]
Développer un programme pouvant prendre en argument un document XML provenant de Moodle et parser ce dernier afin de récupérer ses informations (type d'activités, dates des activités).
[Lien vers le plan d'itération!](https://docs.google.com/document/d/1ZfCmZaw2WZyRf72aBLJnTy593jwzkBZzGKm2wpb87Kg/edit)

**Comment by fuhrmanator** [comment]
Fermé selon les commentaires de #4
