### ISSUE TITLE
Ajouter au programme une fonction pour changer les valeurs des dates des activités Moodle. Créer le nouveau fichier XML.

### ISSUE THREAD

**Issue by denisbressand** [fuhrmanator/course-activity-planner#4]
Les dates des activités peuvent être changées dans le document XML depuis le programme, et un nouveau document XML peut être produit avec les nouvelles dates. Le nouveau fichier pourra être importé manuellement dans un premier temps dans Moodle et on vérifiera que les nouvelles dates soient correctes.
[Lien vers le plan d'itération!](https://docs.google.com/document/d/1ZfCmZaw2WZyRf72aBLJnTy593jwzkBZzGKm2wpb87Kg/edit)

**Comment by fuhrmanator** [comment]
Je pense que c'est mieux de laisser les tâches sous les récits utilisateurs (tels que #1) plutôt qu'en générer d'autres... J'expérimente un peu, mais vu qu'un récit utilisateur est composé de tâches, il suffit de mettre les cases à cocher dans la description du récit utilisateur. Le suivi sera documenté dans les commentaires du récit utilisateur. 

Dans chaque itération, on va choisir les tâches (d'un ou de plusieurs récits utilisateurs) à viser dans l'itération. Le plan d'itération (en dehors de GitHub) fait référence à ces tâches là. Je sais que l'on n'a pas fait exactement ça pour le premier plan, mais ce n'est pas grave. 

L'objectif que tu décris dans cet issue est correct et c'est essentiellement ce que tu vises pour la première itération. La gestion des tâches sera plus fluide pour la deuxième itération. Alors, je ferme cet élément.
