### ISSUE TITLE
Première ébauche de l'architecture du logiciel

### ISSUE THREAD

**Issue by denisbressand** [fuhrmanator/course-activity-planner#5]
Délivrer une première ébauche de l'architecture du logiciel (diagrammes et technologies utilisés).
[Lien vers le plan d'itération!](https://docs.google.com/document/d/1ZfCmZaw2WZyRf72aBLJnTy593jwzkBZzGKm2wpb87Kg/edit)

**Comment by fuhrmanator** [comment]
Fermé selon les commentaires dans #4
